# Generated by Django 5.2 on 2025-05-05 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AracSahibi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi_soyadi', models.CharField(max_length=100, verbose_name='Adı Soyadı')),
                ('firma_adi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Firma Adı (Şirketse)')),
                ('vkn_tckn', models.CharField(max_length=20, unique=True, verbose_name='VKN/TCKN')),
                ('telefon', models.CharField(max_length=20, verbose_name='Telefon')),
                ('adres', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('banka_hesap_bilgisi', models.TextField(blank=True, null=True, verbose_name='Banka Hesap Bilgisi (IBAN vb.)')),
            ],
            options={
                'verbose_name': 'Araç Sahibi / Tırcı',
                'verbose_name_plural': 'Araç Sahipleri / Tırcılar',
            },
        ),
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_adi', models.CharField(max_length=200, verbose_name='Firma Adı')),
                ('vkn_tckn', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='VKN/TCKN')),
                ('adres', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('telefon', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('is_musteri', models.BooleanField(default=True, verbose_name='Müşteri mi?')),
                ('is_tedarikci', models.BooleanField(default=False, verbose_name='Tedarikçi mi?')),
            ],
            options={
                'verbose_name': 'Firma',
                'verbose_name_plural': 'Firmalar',
            },
        ),
        migrations.CreateModel(
            name='Arac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaka', models.CharField(max_length=15, unique=True, verbose_name='Plaka')),
                ('arac_turu', models.CharField(choices=[('Tır', 'Tır'), ('Kamyon', 'Kamyon'), ('Kamyonet', 'Kamyonet'), ('Tenteli', 'Tenteli Dorse'), ('Acik', 'Açık Dorse'), ('SalKasa', 'Sal Kasa Dorse'), ('Lowbed', 'Lowbed Dorse'), ('Diger', 'Diğer')], max_length=50, verbose_name='Araç Türü')),
                ('model_yili', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Model Yılı')),
                ('sasi_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Şasi No')),
                ('sigorta_bitis_tarihi', models.DateField(blank=True, null=True, verbose_name='Sigorta Bitiş Tarihi')),
                ('muayene_bitis_tarihi', models.DateField(blank=True, null=True, verbose_name='Muayene Bitiş Tarihi')),
                ('sahibi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='araclari', to='operations.aracsahibi', verbose_name='Sahibi')),
            ],
            options={
                'verbose_name': 'Araç',
                'verbose_name_plural': 'Araçlar',
            },
        ),
        migrations.CreateModel(
            name='NakliyeKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('takip_no', models.CharField(max_length=50, unique=True, verbose_name='Takip Numarası')),
                ('yuk_adi', models.CharField(max_length=200, verbose_name='Yük Adı/Tanımı')),
                ('nakliye_tipi', models.CharField(max_length=50, verbose_name='Nakliye Tipi (Komple/Parsiyel vb.)')),
                ('miktar', models.CharField(max_length=100, verbose_name='Miktar (örn: 10 Palet)')),
                ('agirlik', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ağırlık (Ton)')),
                ('hacim_ebat', models.CharField(blank=True, max_length=200, null=True, verbose_name='Hacim/Ebat Bilgisi')),
                ('yukleme_adresi', models.TextField(verbose_name='Yükleme Adresi')),
                ('yukleme_tarih_saat', models.DateTimeField(verbose_name='Yükleme Tarih ve Saat')),
                ('bosaltma_adresi', models.TextField(verbose_name='Boşaltma Adresi')),
                ('bosaltma_tarih_saat', models.DateTimeField(verbose_name='Boşaltma Tarih ve Saat')),
                ('anlasilan_bedel', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Anlaşılan Nakliye Bedeli (Aracının Firmadan alacağı)')),
                ('ek_masraflar_firma', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ek Masraflar (Firmadan alınacak)')),
                ('odeme_vadesi', models.DateField(blank=True, null=True, verbose_name='Ödeme Vadesi (Firmadan)')),
                ('aciklamalar', models.TextField(blank=True, null=True, verbose_name='Açıklamalar')),
                ('durum', models.CharField(choices=[('Yeni', 'Yeni Kayıt'), ('Atandı', 'Araca Atandı'), ('Yolda', 'Yolda'), ('Teslim Edildi', 'Teslim Edildi'), ('Faturalandı', 'Faturalandırıldı'), ('Tahsil Edildi', 'Tahsil Edildi'), ('Kapandı', 'Kapandı'), ('İptal Edildi', 'İptal Edildi')], default='Yeni', max_length=50, verbose_name='Durum')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verilen_nakliyeler', to='operations.firma', verbose_name='İşi Veren Firma')),
            ],
            options={
                'verbose_name': 'Nakliye Kaydı',
                'verbose_name_plural': 'Nakliye Kayıtları',
                'ordering': ['-olusturma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='Atama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anlasilan_arac_bedeli', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Anlaşılan Araç Bedeli (Aracının Tırcıya Ödeyeceği)')),
                ('ek_masraflar_arac', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ek Masraflar (Tırcıya ödenecek)')),
                ('atama_tarih_saat', models.DateTimeField(auto_now_add=True, verbose_name='Atama Tarihi ve Saat')),
                ('talimat_notlari', models.TextField(blank=True, null=True, verbose_name='Talimat Notları')),
                ('atanan_arac', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atamalari', to='operations.arac', verbose_name='Atanan Araç')),
                ('atanan_arac_sahibi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verilen_atamalar', to='operations.aracsahibi', verbose_name='Atanan Araç Sahibi / Tırcı')),
                ('nakliye_kaydi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atamalar', to='operations.nakliyekaydi', verbose_name='Nakliye Kaydı')),
            ],
            options={
                'verbose_name': 'Atama',
                'verbose_name_plural': 'Atamalar',
            },
        ),
    ]
