# Generated by Django 5.2 on 2025-05-05 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiderKategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, unique=True, verbose_name='Gider Kategorisi Adı')),
            ],
            options={
                'verbose_name': 'Gider Kategorisi',
                'verbose_name_plural': 'Gider Kategorileri',
            },
        ),
        migrations.RemoveField(
            model_name='firma',
            name='is_musteri',
        ),
        migrations.RemoveField(
            model_name='firma',
            name='is_tedarikci',
        ),
        migrations.AddField(
            model_name='firma',
            name='firma_tipi',
            field=models.CharField(choices=[('Musteri', 'Müşteri (İş Veren)'), ('Tedarikci', 'Tedarikçi (Diğer Hizmetler)'), ('AracSahibi', 'Araç Sahibi (Tırcı)'), ('Diger', 'Diğer')], default='Musteri', max_length=20, verbose_name='Firma Tipi'),
        ),
        migrations.CreateModel(
            name='EFatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fatura_yonu', models.CharField(choices=[('Giden', 'Giden (Satış)'), ('Gelen', 'Gelen (Alış/Gider)')], max_length=10, verbose_name='Fatura Yönü')),
                ('fatura_uuid', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Fatura UUID')),
                ('fatura_numarasi', models.CharField(max_length=50, verbose_name='Fatura Numarası')),
                ('fatura_tarihi', models.DateField(verbose_name='Fatura Tarihi')),
                ('fatura_vadesi', models.DateField(blank=True, null=True, verbose_name='Fatura Vadesi')),
                ('gonderen_vkn_tckn', models.CharField(max_length=20, verbose_name='Gönderen VKN/TCKN')),
                ('gonderen_adi_unvani', models.CharField(max_length=200, verbose_name='Gönderen Adı/Unvanı')),
                ('alan_vkn_tckn', models.CharField(max_length=20, verbose_name='Alan VKN/TCKN')),
                ('alan_adi_unvani', models.CharField(max_length=200, verbose_name='Alan Adı/Unvanı')),
                ('mal_hizmet_toplami', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Mal/Hizmet Toplamı (KDV Hariç)')),
                ('toplam_kdv', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Toplam KDV')),
                ('toplam_tevkifat', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Toplam Tevkifat')),
                ('fatura_toplami', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fatura Toplamı (KDV Dahil)')),
                ('odenecek_tutar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ödenecek/Tahsil Edilecek Tutar')),
                ('durum', models.CharField(choices=[('Taslak', 'Taslak'), ('Gonderildi', "GİB'e Gönderildi"), ('GIB Hata', 'GİB Hata'), ('Aliciya Iletildi', 'Aliciya Iletildi'), ('Kabul Edildi', 'Alıcı Tarafından Kabul Edildi'), ('Reddedildi', 'Alıcı Tarafından Reddedildi'), ('Iptal Edildi', 'İptal Edildi'), ('Muhasebelestirildi', 'Muhasebeleştirildi')], default='Taslak', max_length=50, verbose_name='E-Fatura Durumu')),
                ('xml_dosyasi', models.FileField(blank=True, null=True, upload_to='efaturalar/xml/', verbose_name='E-Fatura XML Dosyası')),
                ('pdf_dosyasi', models.FileField(blank=True, null=True, upload_to='efaturalar/pdf/', verbose_name='E-Fatura PDF Dosyası')),
                ('gib_yaniti_xml', models.FileField(blank=True, null=True, upload_to='efaturalar/yanit/', verbose_name='GİB Yanıt XML Dosyası')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('ilgili_atamalar', models.ManyToManyField(blank=True, related_name='gelen_faturalar', to='operations.atama', verbose_name='İlgili Atamalar (Gelen Fatura İçin)')),
                ('ilgili_nakliye_kayitlari', models.ManyToManyField(blank=True, related_name='faturalar', to='operations.nakliyekaydi', verbose_name='İlgili Nakliye Kayıtları (Giden Fatura İçin)')),
            ],
            options={
                'verbose_name': 'E-Fatura',
                'verbose_name_plural': 'E-Faturalar',
                'ordering': ['-fatura_tarihi', '-olusturma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='IrsaliyeKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('irsaliye_no', models.CharField(max_length=100, verbose_name='İrsaliye Numarası')),
                ('irsaliye_tarihi', models.DateField(verbose_name='İrsaliye Tarihi')),
                ('duzenleyen_firma_adi', models.CharField(max_length=200, verbose_name='Düzenleyen Firma Adı')),
                ('belge_dosyasi', models.FileField(blank=True, null=True, upload_to='irsaliyeler/', verbose_name='Belge Dosyası/Görseli')),
                ('aciklamalar', models.TextField(blank=True, null=True, verbose_name='Açıklamalar')),
                ('kayit_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('nakliye_kaydi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irsaliyeler', to='operations.nakliyekaydi', verbose_name='Nakliye Kaydı')),
            ],
            options={
                'verbose_name': 'İrsaliye Kaydı',
                'verbose_name_plural': 'İrsaliye Kayıtları',
                'ordering': ['-irsaliye_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='Odeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ödeme Tutarı')),
                ('tarih', models.DateField(verbose_name='Ödeme Tarihi')),
                ('odeme_yontemi', models.CharField(choices=[('Nakit', 'Nakit'), ('BankHavaleEFT', 'Banka Havalesi/EFT'), ('Cek', 'Çek'), ('Senet', 'Senet'), ('Diger', 'Diğer')], max_length=50, verbose_name='Ödeme Yöntemi')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='odemeler', to='operations.firma', verbose_name='Ödeme Yapılan Firma/Tedarikçi')),
                ('ilgili_faturalar', models.ManyToManyField(blank=True, related_name='odemeler', to='operations.efatura', verbose_name='İlgili Faturalar')),
            ],
            options={
                'verbose_name': 'Ödeme',
                'verbose_name_plural': 'Ödemeler',
                'ordering': ['-tarih'],
            },
        ),
        migrations.CreateModel(
            name='OtherGider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tutar')),
                ('tarih', models.DateField(verbose_name='Tarih')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('belge_dosyasi', models.FileField(blank=True, null=True, upload_to='diger_giderler/', verbose_name='Belge (Makbuz vb.)')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giderleri', to='operations.giderkategori', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Diğer Gider',
                'verbose_name_plural': 'Diğer Giderler',
                'ordering': ['-tarih'],
            },
        ),
        migrations.CreateModel(
            name='Tahsilat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tahsilat Tutarı')),
                ('tarih', models.DateField(verbose_name='Tahsilat Tarihi')),
                ('odeme_yontemi', models.CharField(choices=[('Nakit', 'Nakit'), ('BankHavaleEFT', 'Banka Havalesi/EFT'), ('Cek', 'Çek'), ('Senet', 'Senet'), ('Diger', 'Diğer')], max_length=50, verbose_name='Ödeme Yöntemi')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tahsilatlar', to='operations.firma', verbose_name='Tahsilat Yapılan Firma')),
                ('ilgili_faturalar', models.ManyToManyField(blank=True, related_name='tahsilatlar', to='operations.efatura', verbose_name='İlgili Faturalar')),
            ],
            options={
                'verbose_name': 'Tahsilat',
                'verbose_name_plural': 'Tahsilatlar',
                'ordering': ['-tarih'],
            },
        ),
        migrations.CreateModel(
            name='TeslimEvragi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teslim_tarih_saat', models.DateTimeField(verbose_name='Teslim Tarih ve Saat')),
                ('teslim_alan_adi', models.CharField(max_length=200, verbose_name='Teslim Alan Kişi/Firma Adı')),
                ('belge_dosyasi', models.FileField(blank=True, null=True, upload_to='teslim_evraklari/', verbose_name='Belge Dosyası/Görseli')),
                ('aciklamalar', models.TextField(blank=True, null=True, verbose_name='Açıklamalar')),
                ('kayit_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('nakliye_kaydi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teslim_evraklari', to='operations.nakliyekaydi', verbose_name='Nakliye Kaydı')),
            ],
            options={
                'verbose_name': 'Teslim Evrağı',
                'verbose_name_plural': 'Teslim Evrakları',
                'ordering': ['-teslim_tarih_saat'],
            },
        ),
    ]
